// test-files/test-svelte.svelte
<script>
  import { onMount } from 'svelte';

  export let name = 'World';
  export let age = 25;

  let count = 0;
  let mounted = false;

  onMount(() => {
    mounted = true;
    console.log('Component mounted');
  });

  function increment() {
    count += 1;
  }

  function decrement() {
    count -= 1;
  }
</script>

<main>
  <h1>Hello {name}!</h1>
  <p>You are {age} years old</p>
  <p>Count: {count}</p>
  <p>Mounted: {mounted}</p>

  <div class="buttons">
    <button on:click={increment}>+</button>
    <button on:click={decrement}>-</button>
  </div>
</main>

<style>
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }

  .buttons {
    display: flex;
    gap: 10px;
    justify-content: center;
  }

  button {
    background: #ff3e00;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
  }

  button:hover {
    background: #d32f00;
  }
</style>

// test-files/test-vue.vue
<template>
  <div class="test-component">
    <h1>{{ title }}</h1>
    <p>{{ message }}</p>
    <button type="button" @click="increment">Count: {{ count }}</button>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';

const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  message: {
    type: String,
    default: 'Hello World',
  },
});

const count = ref(0);

const increment = () => {
  count.value += 1;
};

const doubledCount = computed(() => count.value * 2);
</script>

<style scoped>
.test-component {
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 8px;
}

h1 {
  color: #333;
  margin-bottom: 10px;
}

button {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #0056b3;
}
</style>
